name: Update raw.json from API

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 06:00 UTC

jobs:
  update-raw-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest raw.json from API
        run: |
          if ! curl -sSL "https://sa.ci.ufpb.br/api/paas/center?id=CI" -o remote-raw.json; then
            echo "Failed to download from API"
            exit 1
          fi

      - name: Validate downloaded content
        run: |
          # Check if the downloaded file is valid JSON
          if ! jq empty remote-raw.json 2>/dev/null; then
            echo "Downloaded content is not valid JSON"
            cat remote-raw.json
            exit 1
          fi

          # Check if the content is an error response
          if jq -e '.statusCode or .error' remote-raw.json >/dev/null 2>&1; then
            echo "API returned an error response:"
            cat remote-raw.json
            exit 1
          fi

          # Check if the file is not empty and has meaningful content
          if [ ! -s remote-raw.json ] || [ "$(jq -r 'type' remote-raw.json)" = "null" ]; then
            echo "Downloaded file is empty or contains null data"
            exit 1
          fi

      - name: Compare with current raw.json
        id: compare
        run: |
          if cmp --silent remote-raw.json src/lib/saci/raw.json; then
            echo "No update needed."
            echo "update_needed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Update needed."
            echo "update_needed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Replace raw.json if changed
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          mv remote-raw.json src/lib/saci/raw.json

      - name: Commit and push changes
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/lib/saci/raw.json
          git commit -m "chore: update raw.json from API at $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push

      - name: Clean up temporary file
        if: always()
        run: |
          rm -f remote-raw.json
